# Generated by Django 5.0.4 on 2025-01-02 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='next_article',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_articles', to='blog.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='previous_article',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_articles', to='blog.article'),
        ),
    ]
